try {} catch (e) {
    console.log('PASS');
}
