try {
    console.log(foo());
} catch (e) {
    console.error(e);
}
